Chapter 2 : Linear Regression Multiple Variables


Here we have already a data in which we have to predict there prices of Areas in Monroe Township ,USA and also data contains Bedroom column and age column too

Question 1) Predict the prices of 3000 sqrfeet,3bedrooms,40years old.

Question 2) Predict the prices of 2500 sqrfeet,4bedrooms,5years old

In [4]:
import pandas as pd
from sklearn import linear_model
import numpy as np


In [5]:
df = pd.read_csv('home_prices_in_Monroe.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

So here we have the NaN Value So in the solution we will take Median of the whole column because it will be safe

In [6]:
median_bedrooms = df.bedrooms.median()
median_bedrooms


3.5

 Hence it is 3.5 we will consider only 3

In [7]:
#To Make it 3 we will import math module and will floor the median_bedroom
import math
median_bedrooms = math.floor(median_bedrooms)
median_bedrooms#Here we selected Only 3 from 3.5

3

In [8]:
df.bedrooms.fillna(median_bedrooms)#Filling NA values with Median we got from median()

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [9]:
df.bedrooms =  df.bedrooms.fillna(median_bedrooms)#Storing the new column in exhisting df.bedrooms column

In [10]:
df #Printing New and updated dataframe

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [11]:
#Now Creating Model for Linear Regression for Multiple Variables
reg = linear_model.LinearRegression()
reg.fit(df[["area","bedrooms","age"]],df.price)
#Formula for Multiple Variable is 
# y = (m1*x1)+(m2*x2)+(m3*x3)+b
#m1 = m2 = m3 = reg.coef_
#y = price
#x1 = area
#x2 = bedrooms
#x3 = age
#b = intercept

LinearRegression()

In [12]:
reg.coef_ #Find coeficient of Area and Bedrooms,age

array([   137.25, -26025.  ,  -6825.  ])

In [13]:
reg.intercept_# finding Intercept (b)

383725.0

In [14]:
#Now Predicting the price for Question 1
reg.predict([[3000,3,40]])

/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [15]:
#Now Predicting the price for Question 2
reg.predict([[2500,4,5]])

/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])

In [16]:
#Saving My model using Pickle
import pickle

In [17]:
with open("multiple_variable",'wb')as f:
    pickle.dump(reg,f)

In [18]:
with open("multiple_variable","rb") as f:
 my_modal =   pickle.load(f)

In [19]:
my_modal.coef_

array([   137.25, -26025.  ,  -6825.  ])