# Defination of Cross Validation
It is the processure which says that which one of the Algorithm we should use for Data Modeling. 
It Validate the and evaluate that which algorithm's performance will be good fit for the particular Problem.


# How does k-Fold validation works?
It is like train test split but this works very purely
1) First example: - we will devide our 100 samples into 5 different folds where 1 fold = 20 samples then we will notedown each folds scores with the help of iterations. Any one fold will be for test and rest of the 4 will be trained model.
2) Then we take all scores of 5 Tested folds and we will consider the average Score of all of them

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_digits
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.svm import SVC

digits = load_digits()
logic_model = LogisticRegression()
tree_model = RandomForestClassifier()
svm = SVC()

In [24]:
#First lets split digits datasets into train_test_split 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target , test_size=0.3)

In [ ]:
#Now we will check our all Algorithms one by one
#1) Logistic Regression
logic_model.fit(X_train,y_train)
logic_model.score(X_test,y_test)

In [26]:
#2) Random Forest Classifier
tree_model.fit(X_train,y_train)
tree_model.score(X_test,y_test)

0.9777777777777777

In [21]:
#3) Support Vector Machine
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9833333333333333

In [46]:
#Actually we made a function for to calculate score in with different Algorithms
def get_score(model,X_train,X_test,y_train,y_test):#Taking input as model and train_test_split
    model.fit(X_train,y_train)#Fit the model
    return model.score(X_test,y_test)#Returning the score of the model

In [47]:
get_score( tree_model,X_train,X_test,y_train,y_test)

0.9777777777777777

In [48]:
get_score( svm,X_train,X_test,y_train,y_test)

0.9851851851851852

In [49]:
get_score( LogisticRegression(),X_train,X_test,y_train,y_test)#Logistic Regression

/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9740740740740741

# Hence we tried All the Algorithms one by one and not down the scores but lets try K-fold Technique now

In [96]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)#You have to specify how many folds do you want to make using "n_splits"
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [97]:
#Implimentation of kf.split
#Here we have n_splits = 3 so it divided the fold after every three elements.
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9,0]):
    print(train_index,test_index)

[4 5 6 7 8 9] [0 1 2 3]
[0 1 2 3 7 8 9] [4 5 6]
[0 1 2 3 4 5 6] [7 8 9]


# Now this function is only for Explaining you that how you can select a model for your problem that which model will be best suitable for your problem

In [131]:
from sklearn.model_selection import StratifiedKFold#Stratified KFold is little better than KFold and its Accuracy is also good than Normal KFold
folds = StratifiedKFold(n_splits = 2)

In [132]:
score_logistic=[]#Dummy variable for storing the scores of there particular Algorithm
score_svm=[]
score_tree=[ ]
#Function which will train_test_split the data and target one by one and will store its Scores in the dummy variables
for train_index , test_index in kf.split(digits.data):#Giving input an independent variable such as 'digits.data'
    #Now this below code is normal syntax of X_train and y_train but it is now 3D array so you have to repeat 'digits.data' 2 times and 'digits.target' 2 times
    X_train,X_test,y_train,y_test = digits.data[train_index] , digits.data[test_index], \
                                    digits.target[train_index],digits.target[test_index]
    score_logistic.append(get_score( tree_model,X_train,X_test,y_train,y_test))
    score_svm.append(get_score( logic_model,X_train,X_test,y_train,y_test))
    score_tree.append(get_score( svm,X_train,X_test,y_train,y_test))
  

/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_ite

In [137]:
score_logistic

[0.9365609348914858, 0.9616026711185309, 0.9315525876460768]

In [138]:
score_svm

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [139]:
score_tree

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [ ]:
#Now taking Average of that 3 scores and can say that which model will be best fit


# For taking decision that which algorithm should we use for our particular problem we actually uses Cross Validation but Sci-kit learn already have  the premade function which says the score of this functions and then we will dicide which to use
1) For this we will first import cross_val_score from skitiLearn Library from model_selection

In [152]:
 from sklearn.model_selection import cross_val_score
cross_val_score(logic_model,digits.data,digits.target).mean()

/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_ite

0.9137650882079852

In [186]:
cross_val_score(RandomForestClassifier(n_estimators = 10),digits.data,digits.target).mean()#(first position=Algorithm,X,y)

0.8981878675332714

In [150]:
cross_val_score(svm,digits.data,digits.target).mean()

0.9632838130609718